name: GitHub Snake Game

on:
  # Runs once a day
  schedule:
    - cron: "0 0 * * *"
  # Allows running manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: MATRIX204
          outputs: dist/snake.svg

      - name: Push Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
